### ISSUE TITLE
f5 not quiting in Byobu

### ISSUE THREAD

**Issue by vlcinsky** [jmespath/jmespath.terminal#4]
Debian 8.0 with Gnome, using Byobu.

Byobu has F5 already assigned and I am unable to use it for jpterm.

On gnome-terminal it works well.

One could try to make F5 recognized on input, but it would be nice, if there are other, more intuitive methods to exit the program, e.g. Ctrl-C, which is currently not handled and prints stacktrace.

I would propose any of:
- Ctrl-C
- having a [Quit] button to which I could Tab and Enter to use it.

**Comment by jamesls** [comment]
I like the idea of supporting Ctrl-C to exit.  I don't see any downsides to this.  I'll go ahead and update.
