### ISSUE TITLE
Using stdout and stderr for simplified output of expressions and transformed JSON

### ISSUE THREAD

**Issue by vlcinsky** [jmespath/jmespath.terminal#5]
jpterm can serve two purposes
- shape proper JMESPath expression
- generate output based on given expression

Currently, the program allows (only optionally after using Ctrl-P) to output the expression and does not provide an option to output transfrormed JSON document.
# Proposal
- always output created expression into stderr. 
- always output transformed JSON (as shown in right pane at the exit) document to stdout
- If Ctrl-P was not used during the session, output the current expression to stderr.
- If Ctrl-P was used, output only those expressions, which were current at the Ctrl-P moment.
- When user presses Enter, quit the program (so no need for F5)

This could be further enhanced by means of command line switches:

```
Options:
--no-json-out                               Does not output tranformed JSON
--no-expression-out                    Does not output created expressions
--json-out-file <json-file>             File, to which shall be json output saved
--expression-out-file <expr-file>  File to output expressions to. Use - for stdout.
```

**Comment by jamesls** [comment]
Thanks for the proposal.  I'm definitely in favor of improving the workflow for purpose 2 (which admittedly is not something I had initially thought of as a goal for jpterm but definitely see how this can be really useful).

Forgetting backwards compatibility for a minute, what if instead there was an "output mode" toggle?  So be default it would print out whatever's in the result pane when you exit, but you can toggle the output mode to "expression" such that when jpterm exits it will print out the currently entered expression?  I'm not actually sure how useful the Ctrl-p feature where you can print multiple expressions actually is, and I would be ok with removing that functionality.

Thoughts?

**Comment by jamesls** [comment]
Oh and I should mention there's an existing issue about the F5 exit being improved: https://github.com/jmespath/jmespath.terminal/issues/4

As mentioned in that issue, what about Ctrl-C instead of enter for exiting the terminal?  I'm just concerned people may accidentally push enter and not realize that this will exit jpterm.

**Comment by jamesls** [comment]
https://github.com/jmespath/jmespath.terminal/pull/6 has a suggested implementation which has updated docs explaining how it works along with a GIF demo.  Still not 100% sold on the idea of an output mode, so I'd like to experiment a bit more, but let me know if you have any feedback.
