### ISSUE TITLE
Fix requirement Pygments

### ISSUE THREAD

**Issue by lansman** [jmespath/jmespath.terminal#8]
Now requirement is `Pygments<=2.0,>=1.6`

This is probably a bug, because current last version Pygments **2.0.2** doesn't match it.

If it is, you must exclude from top border minor version so it will became: `Pygments<=2,>=1.6`

**Comment by jamesls** [comment]
Yes, this appears to be a bug.  The intent was to lock to the 1.x major version.  I'll need to evaluate the latest changes in pygments 2.x to figure out if I can support both >=1.6 up to the latest 2, or if I just need to switch to locking to the 2.x major version.

Thanks for reporting.
