### ISSUE TITLE
Use as command line tool

### ISSUE THREAD

**Issue by jasny** [jmespath/jmespath.terminal#9]
Can I use this without any user interaction?

I'd like to be able to do something like

```
jpterm my.json -e '{ foo: a, bar: c.d[:2] }'
```

**Comment by jamesls** [comment]
It's not possible to use jpterm without any user interaction.

However, I am actively working on a jmespath CLI that is exactly what you're asking for, a non interactive command line utility designed for scripting purposes.  Coming soon.
